### ISSUE TITLE
Forgot password JWT Header bug

### ISSUE THREAD

**Issue by tuannqhe151337** [tuannqhe151337/fin-planning-backend#160]
---
name | how to fix | assignees
--- | --- | --- | 
:bug: Forgot password | Change header from 'otp-token' and 'user-token' to 'Authorization' | giangdvhe163178 |
---

## :bug: Bug Report

**Current Behavior**
Forgot password currently use 'otp-token' or 'user-token' header

**Input Code**

`UserController.java`
```java
@PostMapping("/auth/otp")
public ResponseEntity<String> OTPValidate(@Valid @RequestHeader("otp-token") String authHeader, @RequestBody OTPBody otpBody, BindingResult bindingResult) {
...
}
```

```java
@PostMapping("/auth/reset-password")
public ResponseEntity<String> resetPassword(@Valid @RequestHeader("user-token") String authHeader, @RequestBody ResetPasswordBody resetPasswordBody, BindingResult bindingResult) {
}
```

**Expected behavior/code**
Change from
```
@Valid @RequestHeader("otp-token"), @Valid @RequestHeader("user-token")
```
to
```
@Valid @RequestHeader("Authorization") String authHeader
```

**Environment**
- Java version: 22.0.2
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by giangdvhe163178** [comment]
![image](https://github.com/user-attachments/assets/84acc2a9-940e-43d9-b861-865a092c738d)
