### ISSUE TITLE
Expected only CORRECT EXCEL to be able to uploaded OK but JPG file was also uploaded successfully 

### ISSUE THREAD

**Issue by giangdvhe163178** [tuannqhe151337/fin-planning-backend#231]
![image](https://github.com/user-attachments/assets/6ca4722d-698c-404e-a6ff-4727addec216)

**Comment by tuannqhe151337** [comment]
![absodiufahosiudf](https://github.com/user-attachments/assets/3091a6fa-c4c9-43b7-accd-882280c9819b)


Nhớ chạy 
```
npx pnpm i
```
trước khi start server
```
npm run dev
```
đấy.
