### ISSUE TITLE
Term update does not run 

### ISSUE THREAD

**Issue by giangdvhe163178** [tuannqhe151337/fin-planning-backend#256]
![image](https://github.com/user-attachments/assets/7aec2841-3846-43a9-9bca-6a580de01931)

**Comment by tuannqhe151337** [comment]
![aosduifhaosiudfad](https://github.com/user-attachments/assets/3c740a64-73f5-42b0-84ee-e56364558ce0)

Nhớ chạy

```
npx pnpm i 
```
rồi mới chạy server
```
npm run dev
```
đấy

**Comment by tuannqhe151337** [comment]
![ahosidufhapsdf](https://github.com/user-attachments/assets/51e0ee4d-4972-41e4-9b0e-5c82faee91b2)

Nhớ chạy 
```
npx pnpm i
```
trước khi start server
```
npm run dev
```
đấy.
